const parseServingMetadata = (name) => {
  const normalizedName = String(name || '');
  const gramMatch = normalizedName.match(/\((\d+)\s*g\)/i);
  if (gramMatch) {
    const servingGrams = Number(gramMatch[1]);
    return {
      calorieBasisGrams: servingGrams,
      calorieBasisLabel: `${servingGrams} g`
    };
  }

  const spoonMatch = normalizedName.match(/\((\d+)\s*ek\)/i);
  if (spoonMatch) {
    const spoonCount = Number(spoonMatch[1]) || 1;
    const estimatedServingGrams = spoonCount * 20;
    return {
      calorieBasisGrams: estimatedServingGrams,
      calorieBasisLabel: `${spoonCount} evőkanál (~${estimatedServingGrams} g)`
    };
  }

  return {
    calorieBasisGrams: 100,
    calorieBasisLabel: '100 g'
  };
};

const createFood = (name, calories) => ({
  name,
  calories,
  ...parseServingMetadata(name)
});

export const FOOD_DB = {
  'Reggeli ételek': [
    createFood('Zabkása (vízzel)', 62),
    createFood('Zabkása (tejjel)', 110),
    createFood('Tükörtojás (1 db)', 90),
    createFood('Rántotta (2 tojás, olajjal)', 190),
    createFood('Főtt tojás', 155),
    createFood('Ham and Eggs', 240),
    createFood('Müzli (cukrozatlan)', 370),
    createFood('Cornflakes', 360),
    createFood('Görög joghurt (natúr)', 100),
    createFood('Kifli (tejes)', 270),
    createFood('Zsemle (vizes)', 280),
    createFood('Teljes kiőrlésű kenyér', 250),
    createFood('Fehér kenyér', 265),
    createFood('Kalács', 320),
    createFood('Kakaós csiga', 410),
    createFood('Túrós táska', 340),
    createFood('Sajtos pogácsa', 380),
    createFood('Croissant (vajas)', 406),
    createFood('Amerikai palacsinta (1 db)', 90),
    createFood('Bundás kenyér', 230),
    createFood('Körözött', 160),
    createFood('Vaj (10g)', 72),
    createFood('Margarin (10g)', 50),
    createFood('Méz (1 ek)', 60),
    createFood('Sárgabaracklekvár', 240),
    createFood('Mogyorókrém (Nutella)', 540),
    createFood('Avokádó pirítós (1 szelet)', 250),
    createFood('Sült szalonna (bacon)', 540),
    createFood('Virsli (főtt)', 260),
    createFood('Debreceni kolbász', 320),
    createFood('Chia puding (kókusztejjel)', 150),
    createFood('Granola', 450),
    createFood('Puffasztott búza', 350),
    createFood('Kenyérlángos', 280),
    createFood('Melegszendvics (sajtos)', 290),
    createFood('Lágy tojás', 145),
    createFood('Omelett (gombás)', 160),
    createFood('Tojáskrém', 210),
    createFood('Sajtos kifli', 310),
    createFood('Töpörtyűkrém', 450),
    createFood('Korpás keksz', 420),
    createFood('Kefir', 50),
    createFood('Ivójoghurt (gyümölcsös)', 80),
    createFood('Sajtos omlett', 220),
    createFood('Spenótos tojáslepény', 140),
    createFood('Szezámmagos zsemle', 300),
    createFood('Rozskenyér', 259),
    createFood('Bagel', 250),
    createFood('Hummusz', 166),
    createFood('Virsli (baromfi)', 210)
  ],
  'Ebéd és Vacsora (Készételek)': [
    createFood('Húsleves (tésztával)', 45),
    createFood('Gulyásleves (marha)', 110),
    createFood('Bableves (csülökkel)', 150),
    createFood('Gyümölcsleves (tejszínes)', 95),
    createFood('Paradicsomleves', 60),
    createFood('Zöldségleves', 35),
    createFood('Rántott csirkemell', 260),
    createFood('Rántott sajt', 330),
    createFood('Sült csirkecomb', 210),
    createFood('Bolognai spagetti', 180),
    createFood('Carbonara tészta', 250),
    createFood('Lasagne', 190),
    createFood('Pörkölt (sertés)', 180),
    createFood('Csirkepaprikás', 160),
    createFood('Székelykáposzta', 130),
    createFood('Töltött káposzta', 145),
    createFood('Töltött paprika', 120),
    createFood('Paprikás krumpli', 110),
    createFood('Rakott krumpli', 170),
    createFood('Rakott karfiol', 120),
    createFood('Brassói aprópecsenye', 240),
    createFood('Hortobágyi húsos palacsinta', 210),
    createFood('Vadas marha', 230),
    createFood('Cézár saláta (csirkével)', 170),
    createFood('Görög saláta', 110),
    createFood('Pizza (Margherita)', 250),
    createFood('Pizza (Magyaros)', 290),
    createFood('Hamburger (sajtos)', 260),
    createFood('Gyros tál (sült krumplival)', 190),
    createFood('Gyros pitában', 220),
    createFood('Sült hekk', 180),
    createFood('Lazacfilé (sült)', 210),
    createFood('Sushi (átlag)', 140),
    createFood('Rizses hús', 150),
    createFood('Bácskai rizseshús', 160),
    createFood('Lencsefőzelék', 130),
    createFood('Borsófőzelék', 110),
    createFood('Spenót főzelék', 90),
    createFood('Sertéskaraj (natúr)', 170),
    createFood('Bécsi szelet', 280),
    createFood('Cordon Bleu', 290),
    createFood('Sült oldalas', 350),
    createFood('Chilis bab', 140),
    createFood('Túrós csusza', 240),
    createFood('Krumplistészta', 160),
    createFood('Mákos guba', 220),
    createFood('Gombapaprikás', 90),
    createFood('Sütőtökkrémleves', 70),
    createFood('Halászlé (ponty)', 85),
    createFood('Rántott gomba', 160)
  ],
  'Húsok és Halak': [
    createFood('Csirkemell', 110),
    createFood('Csirkecomb (bőr nélkül)', 120),
    createFood('Csirkeszárny', 190),
    createFood('Pulykamell', 105),
    createFood('Sertéskaraj (sovány)', 145),
    createFood('Sertéscomb', 160),
    createFood('Sertésoldalas', 310),
    createFood('Sertés szűzpecsenye', 120),
    createFood('Marhabélszín', 140),
    createFood('Marha rostélyos', 250),
    createFood('Marha hátszín', 180),
    createFood('Darált marhahús (20% zsír)', 250),
    createFood('Vadhús (szarvas)', 110),
    createFood('Nyúlhús', 150),
    createFood('Kacsahús (bőrrel)', 330),
    createFood('Libahús (bőrrel)', 370),
    createFood('Bárányborda', 280),
    createFood('Tőkehal', 80),
    createFood('Hekk', 90),
    createFood('Pisztráng', 120),
    createFood('Ponty', 130),
    createFood('Harcsa', 105),
    createFood('Lazac', 208),
    createFood('Tonhal (konzerv, vizes)', 110),
    createFood('Tonhal (konzerv, olajos)', 200),
    createFood('Garnélarák', 90),
    createFood('Tintahal', 90),
    createFood('Kagyló', 85),
    createFood('Pulyka felsőcomb', 150),
    createFood('Sertéstarja', 240),
    createFood('Téliszalámi', 520),
    createFood('Gépsonka', 110),
    createFood('Csirkemell sonka', 90),
    createFood('Parizer', 220),
    createFood('Szalonna (füstölt)', 650),
    createFood('Disznósajt', 280),
    createFood('Véres hurka', 300),
    createFood('Májas hurka', 350),
    createFood('Kenőmájas', 320),
    createFood('Sült kacsamáj', 450),
    createFood('Füstölt tarja', 260),
    createFood('Serrano sonka', 230),
    createFood('Prosciutto', 220),
    createFood('Bresaola', 170),
    createFood('Cápaharcsa', 90),
    createFood('Kaviár', 260),
    createFood('Báránycomb', 210),
    createFood('Őzhús', 105),
    createFood('Pulyka fasírt', 190),
    createFood('Füstölt kolbász', 420)
  ],
  'Tejtermékek és Tojás': [
    createFood('Tej (1,5%)', 44),
    createFood('Tej (2,8%)', 58),
    createFood('Tej (3,5%)', 64),
    createFood('Habtejszín (30%)', 290),
    createFood('Főzőtejszín (10%)', 120),
    createFood('Tejföl (12%)', 140),
    createFood('Tejföl (20%)', 210),
    createFood('Túró (sovány)', 80),
    createFood('Túró (félzsíros)', 145),
    createFood('Túró rudi (natúr)', 350),
    createFood('Trappista sajt', 350),
    createFood('Edami sajt', 310),
    createFood('Gouda sajt', 350),
    createFood('Cheddar sajt', 400),
    createFood('Ementáli sajt', 380),
    createFood('Mozzarella', 280),
    createFood('Feta sajt', 260),
    createFood('Camembert sajt', 300),
    createFood('Brie sajt', 330),
    createFood('Parmigiano (Parmezán)', 430),
    createFood('Mascarpone', 450),
    createFood('Ricotta', 170),
    createFood('Ömlesztett sajt', 250),
    createFood('Sajtkrém (natúr)', 240),
    createFood('Gorgonzola', 350),
    createFood('Kecskesajt', 260),
    createFood('Juhtúró', 290),
    createFood('Kefir', 50),
    createFood('Joghurt (natúr)', 60),
    createFood('Görög joghurt', 100),
    createFood('Skyr', 65),
    createFood('Tojásfehérje', 52),
    createFood('Tojássárgája', 320),
    createFood('Fürjtojás (1 db)', 14),
    createFood('Vaj', 720),
    createFood('Ghi (tisztított vaj)', 880),
    createFood('Sűrített tej', 320),
    createFood('Kókusztej (konzerv)', 200),
    createFood('Mandulatej', 15),
    createFood('Szójatej', 40),
    createFood('Zabtej', 50),
    createFood('Rizstej', 60),
    createFood('Író', 40),
    createFood('Parenyica sajt', 310),
    createFood('Füstölt sajt', 340),
    createFood('Körözött (bolti)', 180),
    createFood('Puding (vaníliás)', 100),
    createFood('Krémtúró', 160),
    createFood('Joghurtital', 75),
    createFood('Bivalymozzarella', 300)
  ],
  'Zöldségek': [
    createFood('Paradicsom', 18),
    createFood('Paprika (TV)', 20),
    createFood('Kígyóuborka', 15),
    createFood('Vöröshagyma', 40),
    createFood('Fokhagyma', 150),
    createFood('Sárgarépa', 41),
    createFood('Fehérrépa', 40),
    createFood('Zeller', 16),
    createFood('Burgonya', 77),
    createFood('Édesburgonya', 86),
    createFood('Brokkoli', 34),
    createFood('Karfiol', 25),
    createFood('Padlizsán', 25),
    createFood('Cukkini', 17),
    createFood('Spenót', 23),
    createFood('Sóska', 25),
    createFood('Fejes saláta', 15),
    createFood('Jégsaláta', 14),
    createFood('Rukkola', 25),
    createFood('Madársaláta', 20),
    createFood('Zöldborsó', 81),
    createFood('Zöldbab', 31),
    createFood('Fejes káposzta', 25),
    createFood('Lila káposzta', 31),
    createFood('Kelkáposzta', 27),
    createFood('Kelbimbó', 43),
    createFood('Kínai kel', 13),
    createFood('Karalábé', 27),
    createFood('Cékla', 43),
    createFood('Retek', 16),
    createFood('Sütőtök', 45),
    createFood('Spárga', 20),
    createFood('Gomba', 22),
    createFood('Lencse (száraz)', 350),
    createFood('Szárazbab', 340),
    createFood('Csicseriborsó', 140),
    createFood('Kukorica', 86),
    createFood('Póréhagyma', 61),
    createFood('Újhagyma', 32),
    createFood('Articsóka', 47),
    createFood('Mángold', 19),
    createFood('Torma', 110),
    createFood('Édeskömény', 31),
    createFood('Patisszon', 15),
    createFood('Avokádó', 160),
    createFood('Olajbogyó', 115),
    createFood('Savanyú káposzta', 20),
    createFood('Kovászos uborka', 12),
    createFood('Bambuszrügy', 27),
    createFood('Csemegekukorica (konzerv)', 80)
  ],
  'Gyümölcsök': [
    createFood('Alma', 52),
    createFood('Körte', 57),
    createFood('Banán', 89),
    createFood('Eper', 32),
    createFood('Málna', 52),
    createFood('Szeder', 43),
    createFood('Áfonya', 57),
    createFood('Ribizli', 56),
    createFood('Görögdinnye', 30),
    createFood('Sárgadinnye', 34),
    createFood('Őszibarack', 39),
    createFood('Sárgabarack', 48),
    createFood('Szilva', 46),
    createFood('Cseresznye', 63),
    createFood('Meggy', 50),
    createFood('Szőlő', 67),
    createFood('Narancs', 47),
    createFood('Mandarin', 53),
    createFood('Grapefruit', 42),
    createFood('Citrom', 29),
    createFood('Kivi', 61),
    createFood('Ananász', 50),
    createFood('Mangó', 60),
    createFood('Papaya', 43),
    createFood('Gránátalma', 83),
    createFood('Füge (friss)', 74),
    createFood('Füge (szárított)', 250),
    createFood('Mazsola', 300),
    createFood('Datolya', 280),
    createFood('Sárkánygyümölcs', 50),
    createFood('Licsi', 66),
    createFood('Passiógyümölcs', 97),
    createFood('Dió', 650),
    createFood('Mogyoró', 630),
    createFood('Mandula', 580),
    createFood('Kesudió', 550),
    createFood('Pisztácia', 560),
    createFood('Földimogyoró', 570),
    createFood('Egres', 44),
    createFood('Bodza', 73),
    createFood('Homoktövis', 80),
    createFood('Birs', 57),
    createFood('Naspolya', 45),
    createFood('Kókusz', 350),
    createFood('Som', 45),
    createFood('Pomelo', 38),
    createFood('Kumquat', 71),
    createFood('Gojibogyó', 349),
    createFood('Aszalt szilva', 240),
    createFood('Aszalt sárgabarack', 240)
  ],
  'Snackek és Édességek': [
    createFood('Chips (sós)', 530),
    createFood('Tortilla chips', 490),
    createFood('Ropi', 380),
    createFood('Perec (sós)', 380),
    createFood('Pattogatott kukorica', 375),
    createFood('Étcsokoládé (70%)', 550),
    createFood('Tejcsokoládé', 530),
    createFood('Fehér csokoládé', 540),
    createFood('Gumicukor', 340),
    createFood('Pillecukor', 320),
    createFood('Nyalóka', 390),
    createFood('Fagylalt (vanília)', 200),
    createFood('Gyümölcs sorbet', 120),
    createFood('Háztartási keksz', 390),
    createFood('Zabkeksz', 450),
    createFood('Töltött ostya', 520),
    createFood('Müzliszelet', 400),
    createFood('Energiaszelet', 450),
    createFood('Fehérjeszelet', 380),
    createFood('Krémes', 250),
    createFood('Somlói galuska', 300),
    createFood('Dobos torta', 380),
    createFood('Sacher torta', 360),
    createFood('Almás pite', 240),
    createFood('Zserbó', 420),
    createFood('Bejgli (diós)', 400),
    createFood('Puszedli', 370),
    createFood('Gofri', 290),
    createFood('Palacsinta (lekváros)', 180),
    createFood('Kürtőskalács', 320),
    createFood('Túró fánk', 300),
    createFood('Lángos', 350),
    createFood('Baklava', 430),
    createFood('Praliné', 500),
    createFood('Gesztenyepüré', 280),
    createFood('Tiramisu', 270),
    createFood('Rizsfelfújt', 150),
    createFood('Tejberizs', 120),
    createFood('Brownie', 460),
    createFood('Muffin', 350),
    createFood('Sajttorta', 320),
    createFood('Karamell', 400),
    createFood('Mentolos cukorka', 390),
    createFood('Sós mogyoró', 600),
    createFood('Diákcsemege', 480),
    createFood('Vattacukor', 390),
    createFood('Marcipán', 480),
    createFood('Pilóta keksz', 490),
    createFood('Kakaós nápolyi', 510),
    createFood('Sportszelet', 450)
  ]
};

export const FLAT_FOOD_OPTIONS = Object.entries(FOOD_DB).flatMap(([category, foods]) =>
  foods.map((food, index) => ({
    ...food,
    category,
    value: `${category}|${index}`
  }))
);